live_config_reload = true
shell = { program = "/usr/bin/fish" }

[selection]
save_to_clipboard = true

[colors]
draw_bold_text_with_bright_colors = true

[colors.bright]
black = "#575b70"
blue = "#caa9fa"
cyan = "#9aedfe"
green = "#5af78e"
magenta = "#ff92d0"
red = "#ff6e67"
white = "#e6e6e6"
yellow = "#f4f99d"

[colors.normal]
black = "#000000"
blue = "#caa9fa"
cyan = "#8be9fd"
green = "#50fa7b"
magenta = "#ff79c6"
red = "#ff5555"
white = "#bfbfbf"
yellow = "#f1fa8c"

[colors.primary]
background = "#000000"
foreground = "#f8f8f2"

[cursor]
style = "Underline"

[env]
TERM = "xterm-256color"

[font]
size = 12.0
bold = { family = "FiraCode Nerd Font Mono", style = "bold" }
bold_italic = { family = "FiraCode Nerd Font Mono", style = "bold_italic" }
italic = { family = "FiraCode Nerd Font Mono", style = "italic" }
normal = { family = "FiraCode Nerd Font Mono", style = "normal" }

[[keyboard.bindings]]
action = "Paste"
key = "V"
mods = "Control|Shift"

[[keyboard.bindings]]
action = "Copy"
key = "C"
mods = "Control|Shift"

[[keyboard.bindings]]
action = "PasteSelection"
key = "Insert"
mods = "Shift"

[[keyboard.bindings]]
action = "ResetFontSize"
key = "Key0"
mods = "Control"

[[keyboard.bindings]]
action = "IncreaseFontSize"
key = "Equals"
mods = "Control"

[[keyboard.bindings]]
action = "IncreaseFontSize"
key = "Plus"
mods = "Control"

[[keyboard.bindings]]
action = "DecreaseFontSize"
key = "Minus"
mods = "Control"

[[keyboard.bindings]]
action = "DecreaseFontSize"
key = "Minus"
mods = "Control"

[mouse]
hide_when_typing = true

[scrolling]
history = 10000
multiplier = 3

[window]
decorations = "full"
decorations_theme_variant = "Dark"
dynamic_padding = true
title = "Alacritty"
class = { general = "Alacritty", instance = "Alacritty" }
dynamic_title = true
dimensions = { columns = 100, lines = 30 }
